CC=clang++
FLAGS=-std=c++11 -g
ALL=d

all: $(ALL)

a: a.cpp
	$(CC) -o a a.cpp $(FLAGS)
b: b.cpp
	$(CC) -o b b.cpp $(FLAGS)
c: c.cpp
	$(CC) -o c c.cpp $(FLAGS)
d: d.cpp
	$(CC) -o d d.cpp $(FLAGS)
e: e.cpp
	$(CC) -o e e.cpp $(FLAGS)

clean:
	rm -f $(ALL)